export const restaurants = [
    {
      name: 'Le Italiano',
      cuisine: 'Italian',
      rating: 4.5,
      priceForTwo: '$30',
      image: 'food/italian.avif',
    },
    {
      name: 'Taco Fiesta',
      cuisine: 'Mexican',
      rating: 4.0,
      priceForTwo: '$25',
      image: 'food/mexican.avif',
    },
    {
        name: 'Nawab Indian',
        cuisine: 'Indian',
        rating: 4.8,
        priceForTwo: '$30',
        image: 'food/indian.avif',
      },
      {
        name: 'Ichiraku Ramen',
        cuisine: 'Japanese',
        rating: 4.7,
        priceForTwo: '$22',
        image: 'food/japanese.avif',
      },
      {
        name: 'Asia Thai',
        cuisine: 'Thai',
        rating: 4.2,
        priceForTwo: '$20',
        image: 'food/thai.avif',
      },
      {
        name: 'Burger Gourmet',
        cuisine: 'Fast Food',
        rating: 4.7,
        priceForTwo: '$20',
        image: 'food/burger.avif',
      },
      {
        name: 'Korean BBQ',
        cuisine: 'Korean',
        rating: 4.9,
        priceForTwo: '$32',
        image: 'food/korean.avif',
      },
      {
        name: 'Tea Zone',
        cuisine: 'Beverage',
        rating: 4.1,
        priceForTwo: '$17',
        image: 'food/boba.avif',
      },
      {
        name: 'Bagel Bar',
        cuisine: 'Breakfast',
        rating: 4.2,
        priceForTwo: '$15',
        image: 'food/bagel.avif',
      },
      {
        name: 'Dosa Boyz',
        cuisine: 'South Indian',
        rating: 4.3,
        priceForTwo: '$14',
        image: 'food/south-indian.avif',
      },
      {
        name: 'Greek Palace',
        cuisine: 'Greek',
        rating: 4,
        priceForTwo: '$28',
        image: 'food/greek.avif',
      },
      {
        name: 'Shawarama King',
        cuisine: 'Middle East',
        rating: 3.8,
        priceForTwo: '$17',
        image: 'food/shawarma.avif',
      },
    // Add more restaurants as needed
  ];